"use strict";
let PlaceToVisit = ['Bali', 'Santorini', 'Paris', 'London', 'Rome'];
console.log("Orignal order of places to visit:");
console.log(PlaceToVisit);
console.log("Places to visit in Alphabetical Order:");
console.log(PlaceToVisit.sort());
console.log("Orignal order of places to visit:");
console.log(PlaceToVisit);
console.log("Places to visit in Reversed Alphabetical Order:");
console.log(PlaceToVisit.sort().reverse());
console.log("Orignal order of places to visit:");
console.log(PlaceToVisit);
let PlaceToVisit2 = ['Bali', 'Santorini', 'Paris', 'London', 'Rome'];
console.log("Places to visit in Reversed Order:");
console.log(PlaceToVisit2.reverse());
console.log("Places to visit in Back in Orignal Order:");
console.log(PlaceToVisit2.reverse());
let PlaceToVisit3 = ['Bali', 'London', 'Paris', 'Rome', 'Santorini'];
console.log("Places to visit in Sorted Array:");
console.log(PlaceToVisit3);
console.log("Places to visit Array in Reversed Alphabetical Order:");
console.log(PlaceToVisit3.reverse());
